---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---

    
## 網站資料爬取
```{r}
#install.packages("rvest")
library(rvest)
p1<- "https://www.ptt.cc/bbs/LoL/index.html"
p2<- "https://www.ptt.cc/bbs/LoL/index7078.html"
p3<- "https://www.ptt.cc/bbs/LoL/index7077.html"
p4<- "https://www.ptt.cc/bbs/LoL/index7076.html"
p5<- "https://www.ptt.cc/bbs/LoL/index7075.html"
p6<- "https://www.ptt.cc/bbs/LoL/index7074.html"
PttLOL <-c(p1,p2,p3,p4,p5,p6)
dataframAll <-NULL
for(i in PttLOL){
    PttLOLContent<-read_html(i)
post_title <- PttLOLContent %>% 
html_nodes(".title") %>% 
html_text()
post_pushnumber<- PttLOLContent %>% 
html_nodes(".nrec") %>% 
html_text()
post_author<- PttLOLContent %>% 
html_nodes(".author") %>% 
html_text()
    datafram <- data.frame(Title = post_title, PushNum=post_pushnumber, 
                           Author=post_author)
    dataframAll <- rbind(dataframAll,datafram)
    next 
}

PttLOL_posts <- dataframAll
#knitr::kable(
#    PttLOL_posts[1:100,c("Title","PushNum","Author")])

```

## 爬蟲結果呈現
```{r}

knitr::kable(
    PttLOL_posts[1:100,c("Title","PushNum","Author")]) ##請將iris取代為上個步驟中產生的爬蟲資料資料框
```

## 解釋爬蟲結果 
```{r}
str(PttLOL_posts)
#總共爬出111篇文章,其中置底的公告,討論,閒聊文也包含在內
table(PttLOL_posts$Author)
#rainnawind所發的文章數最多,共有7篇.另外有一個數字是6,這是已被刪除的文章數目.
```

解釋解釋解釋解釋

```{r}
#前情提要:我沒有再打LOL,跟他不熟
#置底的公告文的作者rainnawind推測應該是LOL版的版主
#已被刪除的文章,作者ID不會出現在Author的欄位 e.g.(本文已被刪除) [Asiankappa]
#LOL板跟有些版不太一樣,好像沒規定標題[黑特]才可以噓文,感覺不容易被板龜咬
#在計算哪個作者發文數最多時,觀察到好少有人發文篇數是大於2,推斷是LOL版的活躍度相當高,常常有人在上面發問,閒聊,開實況,或是揪團. 
#討論的氣氛熱絡,除了推文回覆,更多是以直接回覆整篇文,可以避免推文海同時可以將資訊更有效率的表達
#這個版也盛行[樂透],可以讓更多人來參與活動賺P幣
```

解釋解釋解釋解釋
人工結論與解釋解釋解釋解釋解釋解釋解釋

